# this is the deCONZ portion of compose.yaml and should be downloaded first into /opt and renamed to compose.yaml
#
# alternatively the lines below the keyword "services" will be copied into an existing /opt/compose.yml
# (re)start docker using command 'docker compose up -d'
#
# download this file using command:
# wget https://github.com/rallyeaon/RasPi-Server/raw/main/deCONZ.yml
#
version: '3'
services:

  deconz:
    image: ghcr.io/deconz-community/deconz-docker:latest
    container_name: deconz
    restart: always
    privileged: true                # This is important! Without it, the deCONZ image won't be able to connect to Conbee II.
    network_mode: host
    volumes:
      - /opt/deCONZ:/opt/deCONZ
    devices:
      - /dev/ttyACM0                # This is the USB device that Conbee II is running on.
    environment:
      - TZ=Europe/Vienna
      - DECONZ_DEVICE=/dev/ttyACM0   # This is the USB device that Conbee II is running on.
      - DECONZ_UID=1111
      - DECONZ_GID=1111
      - DECONZ_WEB_PORT=8080
#
