# this is a compose.yaml-file to run deCONZ stand-alone in a docker/portainer environment if the download is renamed to compose.yaml
#
# However, the lines below the keyword "services" are intended to be copied into an existing /opt/compose.yaml to add deCONZ to the environment
# (re)start docker using command 'docker compose up -d'
#
# download this file using command:
# wget https://github.com/rallyeaon/RasPi-Server/raw/main/deCONZ5.yaml
#
services:
##### ----- deconz ----- ######################################################
  deconz:
    image: ghcr.io/deconz-community/deconz-docker:stable
    container_name: deconz
    restart: always
    privileged: true                # This is important! Without it, the deCONZ image won't>
    network_mode: host
    volumes:
      - /opt/deCONZ:/opt/deCONZ
    devices:
      - /dev/ttyACM0                # This is the USB device that Conbee II is running on.
    environment:
      - TZ=Europe/Vienna
      - DECONZ_DEVICE=/dev/ttyACM0   # This is the USB device that Conbee II is running on.
      - DECONZ_UID=1111
      - DECONZ_GID=1111
      - DECONZ_WEB_PORT=8080
      - DECONZ_START_VERBOSE=1
#
#
#
