# this is a compose.yaml-file to run FHEM stand-alone in a docker/portainer environment if the download is renamed to compose.yaml
#
# However, the lines below the keyword "services" are intended to be copied into an existing /opt/compose.yml to add FHEM to the environment# (re)start docker using command 'docker compose up -d'
#
# download this file using command:
# wget https://github.com/rallyeaon/RasPi-Server/raw/main/fhem.yml
#
version: '3'
services:

  fhem:
    image: ghcr.io/fhem/fhem/fhem-docker:latest
    container_name: fhem
    hostname: fhem
    restart: always
    ports:
      - "1883:1883"
      - "8883:8883"
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"
      - "7072:7072"
    volumes:
      - /opt/fhemdocker/:/opt/fhem/
    environment:
      FHEM_UID: 999
      FHEM_GID: 20
      TZ: Europe/Vienna
#
