# this is a compose.yaml-file to run FHEM stand-alone in a docker/portainer environment if the download is renamed to compose.yaml
#
# However, the lines below the keyword "services" are intended to be copied into an existing /opt/compose.yml to add FHEM to the environment# (re)start docker using command 'docker compose up -d'
#
# download this file using command:
# wget https://github.com/rallyeaon/RasPi-Server/raw/main/fhem.yml
#
version: '3'
services:

  fhem:
    image: ghcr.io/fhem/fhem/fhem-docker:bullseye
    container_name: fhem
    hostname: fhem
    restart: always
    network_mode: host
    volumes:
      - /opt/fhem/:/opt/fhem/
    environment:
      FHEM_UID: 999
      FHEM_GID: 20
      TZ: Europe/Vienna
#
