# this is a compose.yaml-file to run FHEMpy google_weather stand-alone in a docker/portainer environment if the download is renamed to compose.yaml
#
# However, the lines below the keyword "services" are intended to be copied into an existing projects/frontpproxy/compose.yaml to add FHEMpy google_weather to the environment# (re)start docker using command 'docker compose up -d'
#
# download this file using command:
# wget https://github.com/rallyeaon/RasPi-Server/raw/main/googleweather5.yaml
#
services:
##### ----- FHEMpy google_weather ----- ########################################
  fhempy-googleweather:
    image: ghcr.io/fhem/fhempy-docker_google_weather:releases-1.4-beta
    container_name: FHEMpy-google_weather
    hostname: fhempy-googleweather
    restart: always
    networks:
      fhem_net:
        ipv4_address: 172.16.57.5

#
#
