# this is a compose.yaml-file to run mosquitto stand-alone in a docker/portainer environment if the download is renamed to compose.yaml
#
# However, the lines below the keyword "services" are intended to be copied into an existing /opt/compose.yml to add mosquitto to the environment# (re)start docker using command 'docker compose up -d'
#
# download this file using command:
# wget https://raw.githubusercontent.com/rallyeaon/RasPi-Server/refs/heads/main/mosquitto5.yaml
#
#
#
services:
##### ----- mosquitto ----- ###################################################
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - /mnt/NVMeData/myopt/mosquitto:/mosquitto
      - /mnt/NVMeData/myopt/mosquitto/data:/mosquitto/data
      - /mnt/NVMeData/myopt/mosquitto/log:/mosquitto/log
    networks:
      fhem_net:
        ipv4_address: 172.16.57.11
    ports:
      - 1885:1885
      - 9001:9001
#
