# this is a compose.yaml to run nginx & letsencrypt stand-alone in a docker/portainer environment if the download is renamed to compose.yaml
#
# In my installation it is included into the "main"-compose.yaml (w/o "service:") located /mnt/NVMeData/compose
# However, it may also be intended to be stored in /mnt/NVMeData/compose/nginx as compose.yaml
#
# download this file using command:
# wget https://raw.githubusercontent.com/rallyeaon/RasPi-Server/refs/heads/main/nginx_and_letsencrypt.yaml
#
#
#
services:

##### ----- frontproxy ----- ####################################################
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - /mnt/NVMeData/myopt/nginx:/etc/nginx/conf.d:ro
      - /mnt/NVMeData/myopt/certbot/www/:/var/www/certbot/:ro
      - /mnt/NVMeData/myopt/certbot/conf:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    restart: always
#
##### ----- letsencrypt ----- ####################################################
  certbot:
    container_name: letsencrypt
    image: certbot/certbot:latest
    restart: always
    volumes:
      - /mnt/NVMeData/myopt/certbot/www/:/var/www/certbot/:rw
      - /mnt/NVMeData/myopt/certbot/conf/:/etc/letsencrypt/:rw
#
