# this is a compose.yaml-file to run mosquitto stand-alone in a docker/portainer environment if the download is renamed to compose.yaml
#
# However, the lines below the keyword "services" are intended to be copied into an existing /opt/compose.yml to add mosquitto to the environment# (re)start docker using command 'docker compose up -d'
#
# download this file using command:
# wget https://github.com/rallyeaon/RasPi-Server/raw/main/portainer5.yml
#
#
#
##### ----- portainer ----- ####################################################
services:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - portainer_data:/data
      - /opt/portainer/data:/data
    restart: unless-stopped
#
#
#
#
##### ----- network definitions ----- ##########################################
networks:
  fhem_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.57.0/24
          gateway: 172.16.57.1
#
#
##### ----- volume definitions ----- ###########################################
#
volumes:
  portainer_data:
    name: portainer_data
    external: true


