# this is the portainer portion of compose.yaml and should be downloaded first into /opt and renamed to compose.yaml
# prior first start make sure the docker volume 'portainer_data' is available. Otherwise you will end up with an error message.
# Creade the volume using command 'sudo docker volume create portainer_data'
#
# having downloaded this file docker will be started using command 'docker compose up -d'
# 
# The web-Interface will be reachable on RasPi-Server:9443 At initial start a saved portainer-configuration may be imported
# from a backup-file portainer-backup_<yyyy>-<mm>-<dd>_<hh>-<mm>-<ss>.tar.gz which is located in directory "Downloads" of my Mac Mini M1
# Alternatively a new configuration using new userID & password can be created
#
# download this file using command wget https://raw.githubusercontent.com/rallyeaon/RasPi-Server/master/portainer.yml
#
version: '3'
services:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped
#
volumes:
  portainer_data:
    name: portainer_data
    external: true
