# this is a compose.yaml-file to run Portainer stand-alone as a docker/portainer environment if the download is to be renamed to compose.yaml
#
# download this file using command:
# wget https://github.com/rallyeaon/RasPi-Server/raw/main/portainer5.yaml
#
#
#
services:
##### ----- portainer ----- ####################################################
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/NVMeData/myopt/portainer/data:/data
    restart: unless-stopped
#
##### ----- network definitions ----- ##########################################
#networks:
#  fhem_net:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.16.57.0/24
#          gateway: 172.16.57.1
#
#
##### ----- volume definitions ----- ###########################################
#
volumes:
  portainer_data:
    name: portainer_data
    external: true


