# this is a compose.yaml-file to run sonos2mqtt stand-alone in a docker/portainer environment if the download is renamed to compose.yaml
#
# However, the lines below the keyword "services" are intended to be copied into an existing /opt/compose.yml to add sonos2mqtt to the environment
# (re)start docker using command 'docker compose up -d'
#
# download this file using command:
# wget https://raw.githubusercontent.com/rallyeaon/RasPi-Server/refs/heads/main/sonos2mqtt5.yaml
#
services:
##### ----- sonos ----- ########################################################
  sonos:
    image: ghcr.io/svrooij/sonos2mqtt
    container_name: sonos
    restart: unless-stopped
    network_mode: host
    environment:
      - SONOS2MQTT_DEVICE=192.168.57.77 # IP of my SONOS One - Service discover>
      - SONOS2MQTT_MQTT=mqtt://192.168.57.50:1883 #
#      # - SONOS2MQTT_DISTINCT=true # if your want distinct topics
      - SONOS_LISTENER_HOST=192.168.57.50 # Docker host IP
#      # - SONOS_TTS_ENDPOINT=http://sonos-tts:5601/api/generate # If you deplo>
#
