# this is a compose.yaml-file to run FHEMpy tuya_smartlife stand-alone in a docker/portainer environment if the download is renamed to compose.yaml
#
# However, the lines below the keyword "services" are intended to be copied into an existing projects/frontpproxy/compose.yaml to add FHEMpy tuya_smartlife to the environment# (re)start docker using command 'docker compose up -d'
#
# download this file using command:
# wget https://github.com/rallyeaon/RasPi-Server/raw/main/tuya_smartlife5.yaml
#
services:
##### ----- FHEMpy tuya_smartlife ----- ########################################
  fhempy-tuya_smartlife:
    image: ghcr.io/fhem/fhempy-docker_tuya_smartlife:1.4.4
    container_name: FHEMpy-tuya_smartlife
    hostname: fhempy-tuya_smartlife
    restart: always
    networks:
      fhem_net:
#
